### ISSUE TITLE
/websocket returns 500 internal server error

### ISSUE THREAD

**Issue by y-kim** [hyeonsangjeon/youtube-dl-nas#36]
It occurs from the latest docker image.

Logs from the docker instance:

```
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/site-packages/bottle.py", line 868, in _handle

    return route.call(**args)

  File "/usr/local/lib/python3.6/site-packages/bottle.py", line 1748, in wrapper

    rv = callback(*a, **ka)

  File "/usr/src/app/bottle_websocket/plugin.py", line 5, in wrapper

    callback(request.environ.get('wsgi.websocket'), *args, **kwargs)

  File "/usr/src/app/youtube-dl-server.py", line 59, in echo

    msg = WSAddr.wsClassVal.receive()

```

**Comment by hyeonsangjeon** [comment]
The WebSocket handler now detects a normal HTTP request without a WebSocket upgrade and returns `400 WebSocket upgrade required` instead of dereferencing a null socket and producing this `500` traceback.

Closing this as completed. A reverse proxy must still forward the standard WebSocket `Upgrade` and `Connection` headers for the live queue to connect.
